M48
; DRILL file {KiCad 9.0.3+1} date 2025-09-03T21:21:11+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-03T21:21:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X32.488Y-37.585
X32.488Y-40.585
T2
X38.125Y-33.875
X58.5Y-34.1
M30
